### ISSUE TITLE
Improve onboarding from the Mod Manager

### ISSUE THREAD

**Issue by rkollins03** [Picalines/outer-scout-blender#1] opened 2024-08-04 13:45 UTC
I'm not sure if I just cannot read the instructions properly but I'm confused as to how you enable textures when it's imported. I'm not sure where else to ask this but if you could provide a full video instruction it would be awesome.

**Comment by Picalines** [comment] 2024-08-04 14:36
> I'm not sure if I just cannot read the instructions properly

The problem is 100% in the documentation, I would be happy to accept help to make it clearer

> I'm confused as to how you enable textures when it's imported

This is the expected behavior - the addon cuts textures from the planet `.blend` file

You don't need textures from the game to record a video the way I (think) described in the README. The idea is that your final render consists of two parts: a video from the game in the background, and your Blender models on top. That is, you will combine them in the `Compositor` window (refer to the relevant section of the README)

The planet model in this addon is only needed so that you can put character models - it **does not** participate in the rendering process. Its position can also be animated to make it easier to fly around the planet (there is such an example in the README)

> I'm not sure where else to ask this but if you could provide a full video instruction it would be awesome

Unfortunately, I didn't have much free time to create such a video. I would like to first make sure that the tool is working (I or someone will make a full-fledged animation using the addon), and after freezing the features, record some kind of full-fledged instruction

Resolution:
Let's change this issue to "improve documentation" or "add FAQ" (something like this), and I'll make the "video instruction" issue. I can't say when I'll do it (or if I will), but at least I'll leave a note

**Comment by rkollins03** [comment] 2024-08-04 17:47
Yah sorry I figured out that it was not what I thought it originally was apologies. The description on the Mod Loader made it sound completely different. It was more so the "Basic Usage" part of the description that was a bit unclear.

- Open Blender and Outer Wilds at the same time
- Get to the desired location in Outer Wilds and click "create a scene" in the [Outer Scout add-on](https://github.com/Picalines/outer-scout-blender) menu
- The Blender add-on imports a planet model from Outer Wilds and sets it to the desired position
- Put the camera in Blender and animate it
- Click on the record button in the add-on menu!

It just sounded like it would import the scene + textures into a blend file. Looking back I guess this was a little stupid to assume but...

That being said, yes the documentation was fairly confusing but I managed to figure out how to record my player camera, but that was about it. I setup and configured the Camera and Empty by just trying different combinations, which was the thing confusing me the most. Not the Composition part though.

If you do eventually make a video or improve the documentation that would be awesome. Even if it is not a video, but more clear steps with pictures for each part it'd be great. This is an insanely cool mod. I just don't have as much experience with Unity to fill in the unclear steps, so I'm not even sure how to repeat what I did lol.

This is also my first time opening an issue thread on a GitHub post and I didn't really know if this was something to ask in one. I just wanted to contact you about the question.

Appreciate the response, looking forward to the updates.

**Comment by Picalines** [comment] 2024-08-04 18:21
I believe that a big factor in the complexity of perception is two different READMEs. I'll probably remove those "Basic Usage" steps from the README in Mod Loader - so there will be only one source of truth that needs to be updated

I will add a folder with examples, where markdown text and pictures explain how some scenes are made. I'll try to do this sometime this month, if I find the time :/ (see #2)

> This is also my first time opening an issue thread on a GitHub post and I didn't really know if this was something to ask in one. I just wanted to contact you about the question

Welcome to GitHub! It's not difficult for me to answer questions here, but for faster interaction, people usually go to the "Outer Wilds Modding" discord

I will close this issue later when I feel that I have solved the problem with "Basic Usage"

**Comment by Picalines** [comment] 2024-11-24 12:03
Fixed by [this commit](https://github.com/Picalines/outer-scout/commit/ed93de5c2ddf78065359d18c4ef2547e44ba5703)

**Closed as completed by Picalines** 2024-11-24 12:03 UTC
Labels: documentation
