### ISSUE TITLE
Add a clear instructions for AssetStudio exports

### ISSUE THREAD

**Issue by Thecreatre** [Picalines/outer-scout-blender#3] opened 2024-08-31 00:14 UTC
right  as it says on the tin

and yes i  did use asset studio or whatever to extract the twins

also it seems  the addon  is refusing  to use the new   folder i made for the twin extraction (this  might  be the whole reason its  refusing to work, that  internally its still using  the  old  bodies  file path)

(as u can  see its saying orbital (as i n the orbital probe  cannon) not  "the twins" the  name of the new folder)

![image](https://github.com/user-attachments/assets/51dc694f-5030-4679-8d90-0b8541e69044)

**Comment by Thecreatre** [comment] 2024-08-31 00:38
also unrelated (sorta) to this issue but  i dunno where  to ask is that even if this addon isn't in the business of ripping the full  quality versions of the  planets (and or structures) i feel like  u should be  able have the planets on for specifically for reflections  and stuff (this m ight  already be a thing your intended todo but i haven't found anything mentioning  it (and i cant check myself  due to this issue)) **so... question exists now!**  _(albeit i am kind of biased cause i was trying to use this thing originally to try to get a decent model of the OPC (yakow one that acculy has the interior so i dunno))_

**Comment by Picalines** [comment] 2024-08-31 08:12
> ![image](https://github.com/user-attachments/assets/51dc694f-5030-4679-8d90-0b8541e69044)
> 

It seems to me that the addon looks in the 'orbital' folder, but the fbx is actually in the 'Mesh' subfolder, or something like that. Please, provide a screenshot of your addon preferences - it's hard to debug without full context

Note that the addon doesn't do a recursive search of fbx files in subfolders. I can do that, but personally I think it can lead to wrong files being found. I can't just scan your *entire PC* even if the file is there :)

(Also, yeah, I just don't think it's a good idea to do this things in the Downloads. It's your buiseness, I'm just  saying)

**Comment by Picalines** [comment] 2024-08-31 08:23
> this addon isn't in the business of ripping the full  quality versions of the  planets

Currently it's not the intended use case of the addon

The problem is that's impossible (to my understanding) to rip full quality body model. Remember that the addon reads fbx file with static meshes and then searches for dynamic obj files - that's the hardest part, because sometimes it finds wrong model, because it had a similar file name (and there isn't any good method besides looking at the filename)

I don't say it's entirely impossible, I want to say that this algorithm is just too painful to test and debug. On my machine it takes several minutes to generate a planet, and then you have to *look* for wrong things, and also account for the Unity->Blender coordinate conversion, and then it'd fail on some transparent/shader object - I don't want to write cross-rendering-engine-thing :(

Also it's hard because planets actually have dynamic things going on, so there should be some UI accounting for that. I'd be happy if there was a simpler way to do this things, but tbh I just don't know them

**Comment by Thecreatre** [comment] 2024-08-31 15:17
> 
> It seems to me that the addon looks in the 'orbital' folder, but the fbx is actually in the 'Mesh' subfolder, or something like that. Please, provide a screenshot of your addon preferences - it's hard to debug without full context
> 
> Note that the addon doesn't do a recursive search of fbx files in subfolders. I can do that, but personally I think it can lead to wrong files being found. I can't just scan your _entire PC_ even if the file is there :)
> 
> (Also, yeah, I just don't think it's a good idea to do this things in the Downloads. It's your business, I'm just saying)

look that's just how i work unless im  thinking im going to  be spending alot  of time  on it,  anyway

![image](https://github.com/user-attachments/assets/d77bb906-b0f6-4e98-b294-abbcf6a3fd29)

btw am i supposed  to supply the streaming assets? the  documentation is.. sparse so  don't know

**Comment by Picalines** [comment] 2024-08-31 15:32
> btw am i supposed to supply the streaming assets?

Yes, it's documented. `Bodies Folder` is for the planets you've picked in the AssetStudio tree, `Extracted Assets Folder` is for the streamed assets. They have to be separate, because entire file paths matter

<img width="867" alt="image" src="https://github.com/user-attachments/assets/9d0d837d-f8d6-40c0-abd2-258057fda4f0">

And that these folders are not just one planet - you make them on installation, and then export all planets there

<img width="818" alt="image" src="https://github.com/user-attachments/assets/6a53aa26-2f1f-4627-9e31-0854c5d5c675">

You should:
 - Set `Bodies Folder` to `X`, so that the addon would look strictly for `X/<planet_name>.fbx`
 - Export streamed meshes from AssetStudio to `Extracted Assets Folder`, see README steps 5 and 6

**Comment by Thecreatre** [comment] 2024-08-31 16:35
i see, should i reinstall to get  it to change the file path its looking for or something?

**Comment by Picalines** [comment] 2024-08-31 16:40
> i see, should i reinstall to get it to change the file path its looking for or something?

The folder icon on the right side opens a file picker window. That's standard Blender interface

<img width="806" alt="Screenshot 2024-08-31 at 19 38 39" src="https://github.com/user-attachments/assets/26066b6b-c164-4491-9d80-1e7a199d0f48">

**Comment by Thecreatre** [comment] 2024-08-31 16:40
> > btw am i supposed to supply the streaming assets?
> 
> Yes, it's documented. `Bodies Folder` is for the planets you've picked in the AssetStudio tree, `Extracted Assets Folder` is for the streamed assets. They have to be separate, because entire file paths matter
> 
> <img alt="image" width="867" src="https://private-user-images.githubusercontent.com/42614422/363422521-9d0d837d-f8d6-40c0-abd2-258057fda4f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMjIyODMsIm5iZiI6MTcyNTEyMTk4MywicGF0aCI6Ii80MjYxNDQyMi8zNjM0MjI1MjEtOWQwZDgzN2QtZjhkNi00MGMwLWFiZDItMjU4MDU3ZmRhNGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDE2MzMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3OTMzODU4NDg5MGMxMzljMThiMWUzYjIyNGYzMTVlYzhjN2E4ZmI1YWQyM2EwNjZhZWI1YmQ1YTUxNDk2ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q0odfHL4noVpl_262v7TMh-2gUNDyAOyblRXfILpqqw">
> And that these folders are not just one planet - you make them on installation, and then export all planets there

i see, that "important tag" thing i  read and didnt really  understand other than it saying the  fbx  is lower quality  and the  obj is  higher quality but there  in 10 trillion different puzzle pieces

**Comment by Thecreatre** [comment] 2024-08-31 16:41
> > i see, should i reinstall to get it to change the file path its looking for or something?
> 
> The folder icon on the right side opens a file picker window. That's standard Blender interface
> 
> <img alt="Screenshot 2024-08-31 at 19 38 39" width="806" src="https://private-user-images.githubusercontent.com/42614422/363426936-26066b6b-c164-4491-9d80-1e7a199d0f48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMjI3MTMsIm5iZiI6MTcyNTEyMjQxMywicGF0aCI6Ii80MjYxNDQyMi8zNjM0MjY5MzYtMjYwNjZiNmItYzE2NC00NDkxLTlkODAtMWU3YTE5OWQwZjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDE2NDAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZWVlMjQxZjIxZDU0NTViMWI1MDBjYmRmZjc3YjMyZGE1NzZjYjVmNjQxY2E3ZmVlNDYwZmEwODRhMzljMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v8q7Y2bjXQE-LoNhaf0ejzfg9FhyP2YKcamZn-JrpXI">

uh but i did that but its s till looking in the   orbital  folder

**Comment by Thecreatre** [comment] 2024-08-31 16:41
its  mentions the folder when ever  it fails  to make  the scene

**Comment by Thecreatre** [comment] 2024-08-31 16:42
> > ![image](https://private-user-images.githubusercontent.com/177375236/363366901-51dc694f-5030-4679-8d90-0b8541e69044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMjIyODMsIm5iZiI6MTcyNTEyMTk4MywicGF0aCI6Ii8xNzczNzUyMzYvMzYzMzY2OTAxLTUxZGM2OTRmLTUwMzAtNDY3OS04ZDkwLTBiODU0MWU2OTA0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQxNjMzMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTU1ZjY1ZjM0MTkyZjk0Y2E2YzJjMDI5YWY5N2ZlODE4NTQ3MDg5ZTYwMzA1OTc0Y2QzM2M0MTNmZWFjMmJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VYH9lE1g2WLumdl1ICpZIXS_CXcVrDwzqVpZgoPJNyM)


(this)

**Comment by Picalines** [comment] 2024-08-31 16:58
> uh but i did that but its s till looking in the orbital folder

In the first screenshot you have `Downloads\orbital`, but then in the preferences you have `Downloads\The twins` in both paths. The addon can't walk up to `Downloads` and then select `The twins`/`orbital` at random, it doesn't work like that

`Bodies Folder` is used to find `fbx` files just like i described: `X/<planet_name>.fbx`, nothing more. `Extracted Assets Folder` should contain all `obj` files of streamed meshes, and it's inner structure depends on Asset Studio preferences mentioned in the readme

Sorry for the frustration, all instructions are in the readme, and all of them are required. I know there're a lot of details - but that's usually how things work with asset extraction in general

**Comment by Thecreatre** [comment] 2024-09-03 01:23
uh i was showing the screen shot cause its still using the  old  file  path (that screen shot  giving an err about not being able to find tower  twin) but at that  point i had already switched to the twins folder so  i dont know why its still  looking  in orbital (dispite my changed settings)

**Comment by Thecreatre** [comment] 2024-09-03 01:25
basically my preferences where not changed between the time of the first screen shot and the second one (showing  the preferences window)

**Comment by Picalines** [comment] 2024-11-24 12:09
Sorry for the lack of response, sadly I have near to zero time to actively work on the project. Several of my friends are using the addon now, and they were able to successfully set up the addon

I will leave this task open until some video instructions appear

**Comment by Picalines** [comment] 2024-12-24 11:58
We've made a video were you can watch the setup of AssetStudio and other stuff! Again, sorry for a long delay

I'll close the issue for now, but feel free to reopen it

**Closed as completed by Picalines** 2024-12-24 11:58 UTC
Labels: help wanted
